### ISSUE TITLE
Invalid length returned

### ISSUE THREAD

**Issue by neerajvashistha** [tadeck/onetimepass#25]
Hello,

I was just testing the OTP generation using get_totp method and 
`otp.get_totp(my_secret,interval_length = timeout,token_length=length)`
had given 6 as the desired length, I tested it for 100 odd iterations and to my surprise, it returned OTPs for length less than 6 sometimes, like 3 out of 100 were of length 4 or 5. 

`mysecret = base64.b32encode(str(chat_id[0:9]))
timeout = 160
length=6`

Please tell me how to fix this, 

uploading the test results for reference

[out.log](https://github.com/tadeck/onetimepass/files/1684542/out.log)

**Comment by tadeck** [comment]
@neerajvashistha First, thank you for your report!

Looks like what you need is to use `as_string=True` keyword argument. Then the results are strings with proper length. Otherwise you get integers, which do not have lengths obviously (their textual representation has).

If I am correct, every time you receive number with less than 6 digits, you need to prepend it with enough zeros (`0`) to get 6-digit representation as result. This additional argument to the function (`as_string`) does that for you.

When it comes to your log, I understand this is log of responses from some of your services, and `optid` are actual codes generated. In such case, this is barely useful - more useful would be, if you could provide exact parameters, especially `secret` (warning: don't use real secrets used by your clients, and if so, don't tell us about that fact!) and either `intervals_no` (in case of `get_hotp()` function) or `clock` (in case of `get_totp()` function, you would need to set it to Unix epoch seconds and check).

**Comment by tadeck** [comment]
I am closing it. Let me know if you see some issues anyway - will need mentioned data (eg. `secret` and exact time stamp for the time you checked that, with time zone included), expected result, and real result. Will then try to determine what is the problem (if this will indeed come up to be a bug / problem).

**Comment by neerajvashistha** [comment]
Great! I was not aware of `as_string` parameter, I'll definitely try and check. But since it was needed to delivered that day, so I employed another trick and created 6 digit otp without appending 0s as I could not validate these less than 6 digit otp. 

Thanks mate!

**Comment by zdelagrange** [comment]
i am experiencing the same thing, getting a token value with less than the desired length, presumably due to leading 0s.
